name: Webpack-CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install
          npx webpack

      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webpack-bundle-stats
          path: |
            ./dist/bundle-stats.json
            ./dist/bundle-stats.html