name: Webpack-CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Node Modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != true
        run: |
          npm install

      - name: Run Webpack
        run: npx webpack

      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webpack-bundle-stats
          path: |
            ./dist/bundle-stats.json
            ./dist/bundle-stats.html
